### ISSUE TITLE
CV Admin

### ISSUE THREAD

**Issue by dwhieb** [dwhieb/danielhieber.com#137]
- [x] write CV Admin controller (`src/pages/admin/cv.js`)
- [x] write CV Admin LESS (`less/admin/cv.js`)
- [x] write pre-trigger for uploading CV items (#191)
  - checks whether the `cvid` already exists
- [x] for each type of CV item:
  - [x] ~~create JSON Schemas~~
    - will use validation logic and JSDoc comments to document model structure instead
  - [x] write unit tests for server-side models (#128)
  - [x] create server-side models (#142)
    - no base model is necessary for CV items
  - [x] add commenting for server-side models (#145)
  - [x] add `cvid` to server models (#161)
  - [x] ~~create client-side models~~ make a generic client-side Model (#162)
    - this should work for any of the server-side models
    - it should have generic CRUD methods that make calls to the socket
  - [x] ~~add commenting for client-side models (#163)~~ (cf. #162)
  - [x] ~~write unit tests for client-side models (#164)~~ (cf. #162)
  - [x] create HTML templates for form views
    - create one for the Category View as well, and update its logic
  - [x] create form views (`/views/forms/{type}.js`)
    - include `category-view.js` in this folder
- [x] write a generic list view (#173)
  - use your current Categories View as a starting point
- [x] add socket routes for operations on CV items
- [x] add socket handlers for operations on CV items
  - decouple database calls from handlers
  - socket handlers should be minimal functions that call generic CRUD operations on the database
- [x] write unit tests for socket operations on CV items
- [x] `less/admin/cv.less`
  - move categories.less > /admin/categories.less
  - change LESS build script to recursively build subfolders
  - try to make generic form styling, rather than separate styles for each type of CV item
  - if possible, abstract this CSS to admin.less, and delete categories.less and cv.less
- [x] `src/admin/cv.js`
  - move categories.js > /admin/categories.js
