### ISSUE TITLE
home page

### ISSUE THREAD

**Issue by dwhieb** [dwhieb/danielhieber.com#274]
- [x] page
- [x] content
  - ~~better singing picture (with you looking straight ahead)~~ (prefer to keep the original)
- [x] styling
- [x] ~~Me on the Web~~ (moved to #348)
- [x] ~~Latest Blog Posts~~ (moved to #349)
- [x] ~~Goodreads~~ (moved to #350)
