### ISSUE TITLE
CV page

### ISSUE THREAD

**Issue by dwhieb** [dwhieb/danielhieber.com#285]
* design for print layout (using Prince if necessary)
* use package.json and other computed data where possible
* centered, with maximum rule
* do not display hidden CV items
* each CV item should have a hash with its CVID

# Initial Launch
- [x] check that all items from current print version are included in both online and new print version
- [x] headshot (fixed in upper right corner) (#401)
- [x] last updated (based on most recently updated document) (#402)
- [x] TOC (#403)
- [x] `Print / Download` button (use `window.print()`) (#406)

# Wish List
- [x] include page numbers on print version (#404)
- [ ] include Me on the Web partial (#409)
- [ ] make sections collapsible (#405)
- [ ] add `Show / Collapse All Sections` button (#407)
- [ ] allow filtering CV by category (#408)
- [ ] allow live filtering of CV items using a search box (#410)
- [ ] add subroutes for individual CV items (by CVID) (#411)
